name: artifacts

on:
  push:
    branches: main

permissions:
  contents: write   # required for pushing

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello > world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt

  download-artifact:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/download-artifact@v5
        with:
          name: my-artifact
          path: artifact

      - run: mv artifact/world.txt world.txt

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet world.txt; then
            echo "No changes detected"
            exit 0
          fi

          git add world.txt
          git commit -m "Add world.txt from artifact [skip ci]"
          git push
