name: artifacts

on: 
  push:
    branches: main

jobs:
  upload-artifact:
    name: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - run: docker info > world.txt
      - run: echo hello > world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt

  download-artifact:
    name: download-artifact
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R

      #save artifact in repo
    - uses: actions/checkout@v4
    - run: |
          git config user.name "warhe8d"
          git config user.email "59991459+WARHE8D@users.noreply.github.com"
          git add world.txt
          git commit -m "Add world.txt from artifact" || echo "No changes to commit"
          git push
